nodeLinker: node-modules

packageExtensions:
  'vscode-glass@*':
    dependencies:
      '@esbuild/darwin-arm64': '*'
      '@esbuild/darwin-x64': '*'
      '@esbuild/linux-arm64': '*'
      '@esbuild/linux-x64': '*'
      '@esbuild/win32-arm64': '*'
      '@esbuild/win32-x64': '*'

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64]
