name: Publish

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Install jq
        run: sudo apt-get install jq

      - run: npm run build

      - run: npx --workspace vscode-glass vsce package

      ## required fpr the next step
      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn set version stable

      - name: Bundle esbuild
        run: npm run patch:esbuild --workspace=vscode-glass

      # - run: npx ovsx publish --packagePath *.vsix
      #   env:
      #     OVSX_PAT: ${{secrets.OPEN_VSX_TOKEN}}
      - run: npx vsce publish --packagePath *.vsix
        working-directory: ./apps/vscode-glass
        env:
          VSCE_PAT: ${{secrets.VSCE_TOKEN}}

      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{github.workspace}}/apps/vscode-glass/CHANGELOG.md
          files: |
            apps/vscode-glass/*.vsix
